kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    cosckoya.io/monitoring: alertmanager
data:
  config.yml: |-
    global:
      smtp_from: 'admin@cosckoya.io'
      smtp_require_tls: false
      smtp_hello: "helolala"
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_auth_username: 'admin@cosckoya.io'
      smtp_auth_password: '1234567890ABC'

    templates:
    - '/alertmanager/templates/*.tmpl'

    route:
      receiver: 'alerting'
      group_by: ['message', 'pod', 'instance', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15m

      routes:
      - match:
          namespace: 'monitoring'
        receiver: 'admin'

      - match:
          namespace: 'kube-system'
        receiver: 'admin'

      - match_re:
          namespace: ^(frontend|backend|device)$
        receiver: 'developers'

    inhibit_rules:
    - source_match:
        severity: 'Disaster'
      target_match:
        severity: 'High'
      equal: ['alertname']

    receivers:
    - name: developers
      email_configs:
      - send_resolved: true
        to: 'dev@cosckoya.io, me@cosckoya.io'
        headers:
          Subject: "({{.Status}}): {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }})"

    - name: admins
      email_configs:
      - send_resolved: true
        to: 'admin@cosckoya.io, me@cosckoya.io'
        headers:
          Subject: "({{.Status}}): {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }})"
#        html: |
#          Hi Admin,
#          <p>
#          You have the following firing alerts:
#          <ul>
#          {{ range .Alerts }}
#          <li>{{.Labels.alertname}} on {{.Labels.instance}}</li>
#          <li>Labels:</li>
#          <li>{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
#          <li>{{ end }}Annotations:</li>
#          <li>{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
#          <li>{{ end }}---</li>
#          {{ end }}
#          </ul>
#          </p>
