apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-cleanup
  namespace: infrastructure
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        operations.cosckoya.io/infrastructure: docker-cleanup
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      serviceAccountName: cleanup
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: docker-cleanup
        image: docker-registry.cosckoya.io.lab:5000/operations/infrastructure/cleanup:1.1
        command: ["/bin/bash"]
        args: ["-c", "/bin/clean-docker.sh", "2>&1"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 256mi
          requests:
            cpu: 100m
            memory: 64Mi
        env:
        - name: DOCKER_CLEAN_INTERVAL
          value: "28800"
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
