apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cleanup
rules:
  - apiGroups: ["*"]
    resources: ["replicasets", "jobs", "pods"]
    verbs: ["get", "list", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cleanup
subjects:
- kind: ServiceAccount
  name: cleanup
  namespace: infrastructure
