name: Cloud sysutil Containers
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in DockerHub
      run: echo "${{ secrets.dockerhub }}" | docker login https://index.docker.io/v1/ -u ${{ github.actor }} --password-stdin
    - name: AWS build container
      run: docker build . --file cloud/aws --tag cosckoya/sysutils:aws-${GITHUB_SHA::8}
    - name: AZURE build container
      run: docker build . --file cloud/azure --tag cosckoya/sysutils:azure-${GITHUB_SHA::8}
    - name: GCP build container
      run: docker build . --file cloud/google --tag cosckoya/sysutils:gcp-${GITHUB_SHA::8}
    - name: AWS tag container
      run: docker tag cosckoya/sysutils:aws-${GITHUB_SHA::8} cosckoya/sysutils:aws
    - name: AZURE tag container
      run: docker tag cosckoya/sysutils:azure-${GITHUB_SHA::8} cosckoya/sysutils:azure
    - name: GCP tag container
      run: docker tag cosckoya/sysutils:gcp-${GITHUB_SHA::8} cosckoya/sysutils:gcp
    - name: AWS push latest image
      run: docker push cosckoya/sysutils:aws
    - name: AWS push commit image
      run: docker push cosckoya/sysutils:aws-${GITHUB_SHA::8}
    - name: AZURE push latest image
      run: docker push cosckoya/sysutils:azure
    - name: AZURE push commit image
      run: docker push cosckoya/sysutils:azure-${GITHUB_SHA::8}
    - name: GCP push latest image
      run: docker push cosckoya/sysutils:gcp
    - name: GCP push commit image
      run: docker push cosckoya/sysutils:gcp-${GITHUB_SHA::8}
